# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0db350dea6b3c791615abf3b810638e92ab8f944f035339966018b280eacd8982aee7e0e0fcb80d4b5cfa9b29bae7e61794258df015bd0951309ba56fdf29e8

test:
  secret_key_base: d0c7c16b6ca291a1ef9d66d6958a613226cb533d011c0943a710cd8ce3db6727245952020550c1ab424a456f260d53be708de17db337c61f45b415e31491184f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
